apiVersion: v1
kind: Service
metadata:
  name: cert-test
spec:
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: cert-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-test
spec:
  selector:
    matchLabels:
      app: cert-test
  replicas: 2
  template:
    metadata:
      labels:
        app: cert-test
    spec:
      containers:
      - name: cert-test
        image: hashicorp/http-echo
        args:
        - "-text=Hello from TannDev-on-Kubernetes!<br/>Is this over HTTPS?"
        ports:
        - containerPort: 5678
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cert-test-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - cert-test.tanndev.com
    secretName: cert-test-tls
  rules:
  - host: cert-test.tanndev.com
    http:
      paths:
      - backend:
          serviceName: cert-test
          servicePort: 80
