apiVersion: v1
kind: Namespace
metadata:
  name: maelstrom
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: maelstrom-ingress
  namespace: maelstrom
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - maelstrom.tanndev.com
    secretName: maelstrom-tls
  rules:
  - host: maelstrom.tanndev.com
    http:
      paths:
      - backend:
          serviceName: maelstrom
          servicePort: 80
